### ISSUE TITLE
Runtime error on CUDA

### ISSUE THREAD

**Issue by arianaa30** [pedbrgs/Fire-Detection#1]
I have a hard time running it. I guess because the code is for a few years ago and I get issues with new API & A100 GPU etc.
Is there any plans to test or address issues with newer library versions, new GPUs, etc?

```
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by pedbrgs** [comment]
No, I have no intention of working with new versions of libraries at the moment. I even provided dependencies in [requirements.txt](https://github.com/pedbrgs/Fire-Detection/blob/main/requirements.txt) to make the environment reproducible and code easy to run. I also have plans to create a Docker image for the repository.

**Comment by pedbrgs** [comment]
@arianaa30 I just added a Docker image to the repository. Follow the steps in [Tutorial](https://github.com/pedbrgs/Fire-Detection#tutorial) to run the models. 

If you like the work and want to help us spread it to the community, please star the repository. Thank you very much once again for your interest.
