### ISSUE TITLE
Show fire/smoke detections?

### ISSUE THREAD

**Issue by arianaa30** [pedbrgs/Fire-Detection#2]
I am running the model with `python3 baseline.py --video ex1.mp4 --model mobilenet`, but it only shows some bash outputs and no output videos. Does it save the output file somewhere? 

```
1/1 [==============================] - 0s 25ms/step
Time taken =  0.04462027549743652
Prediction: non_fire
1/1 [==============================] - 0s 25ms/step
Time taken =  0.043842315673828125
Prediction: non_fire
1/1 [==============================] - 0s 26ms/step
Time taken =  0.04700660705566406
Prediction: non_fire
1/1 [==============================] - 0s 27ms/step
Time taken =  0.050565481185913086
Prediction: non_fire
Results
     video    network  detected  first_frame  time_avg
0  ex1.mp4  mobilenet      True           10  0.049584
```

**Comment by pedbrgs** [comment]
Yes, it is in the [How to run a hybrid system](https://github.com/pedbrgs/Fire-Detection/blob/main/README.md#how-to-run-a-hybrid-system) section of the [README.md](https://github.com/pedbrgs/Fire-Detection/blob/main/README.md) file.

> After running the system, the videos with the detections are saved in `runs/detect/exp/`.

I suggest you read it in full. There's a lot of useful information there.
