### ISSUE TITLE
Is baseline models for Fire only?

### ISSUE THREAD

**Issue by tjasmin111** [pedbrgs/Fire-Detection#3]
I was trying your baseline models (Firenet and Mobilenet). Are they for Fire only and not Smoke?
`python baseline.py --video <video_file> --model firenet`

**Comment by pedbrgs** [comment]
Hi @tjasmin111! Thank you very much for your interest in our work!

The FireNet network was trained on a dataset with fire and smoke, but the MobileNet network was trained on a dataset with only fire images. However, the FireNet network is not very accurate for smoke detection. In that case, I suggest you use one of our approaches (YOLOv5 + AVT or YOLOv5 + TPT).

You can see more details in our paper:

- <p align="justify"><b>Pedro Vinícius Almeida Borges de Venâncio</b>, Roger Júnio Campos, Tamires Martins Rezende, Adriano Chaves Lisboa, Adriano Vilela Barbosa: <a href="https://link.springer.com/article/10.1007/s00521-023-08260-2"> A hybrid method for fire detection based on spatial and temporal patterns. </a> In: Neural Computing and Applications, 2023.</p>

**Comment by tjasmin111** [comment]
Ok thank you for explaining this. But I don't knownwhy I have difficulty running your models. Baseline.py runs nicely but can't run detect.py at all

**Comment by pedbrgs** [comment]
Did you install the dependencies in a Python environment? See the [Dependencies](https://github.com/pedbrgs/Fire-Detection#dependencies) section.

**Comment by tjasmin111** [comment]
Yes. It would be best if you could have it as a docker image.

**Comment by pedbrgs** [comment]
@tjasmin111 I just added a Docker image to the repository. Follow the steps in [Tutorial](https://github.com/pedbrgs/Fire-Detection#tutorial) to run the models. 

If you like the work and want to help us spread it to the community, please star the repository. Thank you very much once again for your interest.

**Comment by arianaa30** [comment]
Great thanks. I will try it. I already starred the repo

**Comment by tjasmin111** [comment]
I tried it and the detections are pretty good. Was the model trained only on the D-fire dataset?

**Comment by pedbrgs** [comment]
@tjasmin111 I'm glad the results were pretty good. Yes, the model was trained only with images from the D-Fire dataset.
