### ISSUE TITLE
Help with some configuration values

### ISSUE THREAD

**Issue by hahv** [pedbrgs/Fire-Detection#4]
Thank you for your work "A hybrid method for fire detection based on spatial and temporal patterns (2023)". 

My question is:

- *About test video*:  Is a video start with "FP" is the positive video (having fire/smoke) and those starting with "VP" is the negative sample?
The video:
![image](https://github.com/pedbrgs/Fire-Detection/assets/8085290/6aee4847-d5ee-49b2-8c3e-a48769f21252)

- *About the result table 3*:  are you use these following values as provided in the code (or the different ones) to produce this result table?
```
 + conf_thres=0.25,  # confidence threshold
 + iou_thres=0.45,  # NMS IOU threshold"
```
Result table: ![image](https://github.com/pedbrgs/Fire-Detection/assets/8085290/9b706a06-5521-438d-a4cd-761aacc980c5)

Thank you for your clarification!

**Comment by pedbrgs** [comment]
Hi, @hahv! Thank you for your interest in our work!

> About test video: Is a video start with "FP" is the positive video (having fire/smoke) and those starting with "VP" is the negative sample?

No, it's the opposite. The suffix "FP" is for false positive videos (challenging scenarios without fire and smoke), and the suffix "VP" is for true positive videos (with fire and/or smoke).

> About the result table 3: are you use these following values as provided in the code (or the different ones) to produce this result table?

Yes, we use these default values. However, it is important to highlight the section where we explain how we calculated these metrics in the table, as follows.

> Figure 6 shows the inﬂuence of the hyperparameters on the performance of the hybrid systems according to the true positive rate (TPR) and the false positive rate (FPR). In calculating these evaluation metrics, we consider (i) a true positive (TP) if there is a ﬁre in the video and the system detects it in at least one video frame, (ii) a false positive (FP) if there is no ﬁre in the video and the system detects one in at least one video frame, (iii) a true negative (TN) if there is no ﬁre in the video and the system does not detect a ﬁre in any video frame, and (iv) a false negative (FN) if there is a ﬁre in the video and the system does not detect it in any video frame. We chose this evaluation method, where a video is evaluated according to the predictions in all its frames, because we think it is more appropriate for real-time applications. If the model predicts a false positive in a single frame of the video, we assume that it misses the entire video, as this error would possibly trigger a false alarm in such a situation, causing unnecessary ﬁreﬁghter efforts.

I hope this helped. If you appreciate our work and would like to help us share it with the community, please consider starring the repository. Thank you once again for your interest.
