### ISSUE TITLE
How can convert yolov5 to yolov8

### ISSUE THREAD

**Issue by nghharr** [pedbrgs/Fire-Detection#5]
Hi, I want to ask how can I convert this code into yolov8 format to use with temporal features after detection? Please tell me how can I do this?

**Comment by pedbrgs** [comment]
Hi, @nhiennguyenthi0701. I appreciate your interest in my work.
Unfortunately, I haven't had the time to thoroughly explore the repository of YOLOv8. I recommend searching for the source code responsible for making predictions on video frames within the [Ultralytics repository](https://github.com/ultralytics/ultralytics/tree/main). You should look for a script similar to [detect.py](https://github.com/pedbrgs/Fire-Detection/blob/main/detect.py). From this code, it should be relatively straightforward to make the necessary adjustments to incorporate the proposed temporal techniques.
