### ISSUE TITLE
Can i run your tiny-yolov4 on this repo,  i see tiny-yolov4.weights but this repo seem not have code to run with

### ISSUE THREAD

**Issue by GloryVu** [pedbrgs/Fire-Detection#7]

**Comment by pedbrgs** [comment]
Hi @GloryVu! Thank you for your interest in my work! This repository does not include the code required to run the tiny and large YOLOv4 models. To use these models, please download the weights and follow the inference tutorial provided in the official [Darknet repository](https://github.com/AlexeyAB/darknet).
